### ISSUE TITLE
Travel Alerts

### ISSUE THREAD

**Issue by mjdavidson** [consindo/waka#95] opened 2017-11-17 01:26 UTC
Maybe by putting a footer at the bottom of the stop

**Comment by ghost** [comment] 2017-11-17 01:42
I am assuming that you mean push notifications? And if so, how does adding a footer deal with that?

**Comment by mjdavidson** [comment] 2017-11-17 01:48
sorry it’s notifications about travel impact due to oncoming events, roadworks, bus stop changes and motorway info. 

https://api.at.govt.nz/v2/notifications/

**Comment by ghost** [comment] 2017-11-17 19:19
oh okay, that makes more sense

**Comment by consindo** [comment] 2017-12-07 21:23
Duplicate of #38

**Closed as completed by consindo** 2017-12-07 21:23 UTC
